//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 05:10:16 PM CET 
//


package com.hskme.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for word complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="word">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_upt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="traditional" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="simplified" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pinyin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="translations" type="{http://www.dalongma.fr/ws/cfdict}translations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "word", propOrder = {
    "id",
    "timeUpt",
    "traditional",
    "simplified",
    "pinyin",
    "translations"
})
public class WordDto {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "time_upt")
    protected int timeUpt;
    @XmlElement(required = true)
    protected String traditional;
    @XmlElement(required = true)
    protected String simplified;
    @XmlElement(required = true)
    protected String pinyin;
    @XmlElement(required = true)
    protected TranslationsDto translations;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the timeUpt property.
     * 
     */
    public int getTimeUpt() {
        return timeUpt;
    }

    /**
     * Sets the value of the timeUpt property.
     * 
     */
    public void setTimeUpt(int value) {
        this.timeUpt = value;
    }

    /**
     * Gets the value of the traditional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraditional() {
        return traditional;
    }

    /**
     * Sets the value of the traditional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraditional(String value) {
        this.traditional = value;
    }

    /**
     * Gets the value of the simplified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimplified() {
        return simplified;
    }

    /**
     * Sets the value of the simplified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimplified(String value) {
        this.simplified = value;
    }

    /**
     * Gets the value of the pinyin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * Sets the value of the pinyin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinyin(String value) {
        this.pinyin = value;
    }

    /**
     * Gets the value of the translations property.
     * 
     * @return
     *     possible object is
     *     {@link Translations }
     *     
     */
    public TranslationsDto getTranslations() {
        return translations;
    }

    /**
     * Sets the value of the translations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Translations }
     *     
     */
    public void setTranslations(TranslationsDto value) {
        this.translations = value;
    }

}
